More skeletal stuff from Ferdy's spark release

diff --git a/packages/mongodb-service-adapter/packaging b/packages/mongodb-service-adapter/packaging
--- a/packages/mongodb-service-adapter/packaging
+++ b/packages/mongodb-service-adapter/packaging
@@ -1,2 +1,19 @@
-# abort script on any command that exits with a non zero value
-set -e
+#!/bin/bash
+
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
+
+# Set Golang dependency
+export GOROOT=$(cd "/var/vcap/packages/golang" && pwd -P)
+export PATH=${GOROOT}/bin:${PATH}
+
+# Build mongodb service adapter
+mkdir -p ${BOSH_COMPILE_TARGET}/go/src
+mv ${BOSH_COMPILE_TARGET}/mongodb-service-adapter ${BOSH_COMPILE_TARGET}/go/src
+cd ${BOSH_COMPILE_TARGET}/go/src/mongodb-service-adapter
+export GOPATH=${BOSH_COMPILE_TARGET}/go
+go build -o out/mongodb-service-adapter cmd/mongodb-service-adapter/main.go
+
+# Copy mongodb service adapter
+mkdir -p ${BOSH_INSTALL_TARGET}/bin
+cp -a ${BOSH_COMPILE_TARGET}/go/src/mongodb-service-adapter/out/mongodb-service-adapter ${BOSH_INSTALL_TARGET}/bin/
